template_type: TF
terraform_version: 0.12
terraform_012_parameters:
  - root_module: iac-api-v1
#
#template_version: 0.12
#template_parameters:
#  - root_module: iac-api-v2
#    variable_files:
#    - iac-api-v2/variables.tf
#
tags:
  team: Wells