# This is the configuration file for Iac Scan APIv2.

# Specify the template types.The valid values are TF, CFT, K8S
template_type: TF

# For Terraform, it is recommended to provide one of the following values: 0.11, 0.12 or 0.13.
# For CFT and K8s, this can be omitted.
template_version: 0.12

# For your template_type, fill in the details where applicable.
# variables: Specify any environment variables(TF) or parameters(CFT) as key:value pairs under this attribute.
# variable_files: Specify all the custom variable_files under here. It is an array of strings.
# variable_files: If it is standard extension(.tfvars for terraform), then this can be omitted.
# variable_files: For a custom extension, specify the variable file path from the root of the repo.
template_parameters:
  variable_files:
  - './TF/tf12_variable_files/smelks.tfvars'
  - './TF/tf12_nested_variable_files/network/smelks.tfvars'
  variables:
    cidr: 0.0.0.0/0
    acl: public-read-write
    AccessControl: PublicRead

# Define tags to identify your particular scan. You can use these tags to search the scan details on the Prisma Cloud.
tags:
  Org: Engineering
  Team: Shift_Left
  Env: Dev
					
