- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install checkov
  displayName: 'Install Checkov'
- script: checkov -d terragoat --bc-api-key 68570819-c42e-466b-83f9-f6e52c1386b5::9cY0/JybRHT6WNHBAe4OeYGCXB8= --repo-id abheemarao/terragoat --branch master
  displayName: 'Scan with Prisma Cloud'
  env:
    PRISMA_API_URL: api4.prismacloud.io
