
version: 0.2
env:
  variables:
      BC_SOURCE: "codebuild"
      PRISMA_API_URL: "https://api.prismacloud.io"
  parameter-store:
      BC_API_KEY: "bc-api-key"
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
       - pip3 install checkov
       - echo Installing codebuild-extras...
       - curl -fsSL https://raw.githubusercontent.com/bridgecrewio/aws-codebuild-extras/master/install >> extras.sh
       - . ./extras.sh
  build:
    commands:
       - pip3 uninstall -y aws-sam-cli
       - checkov -d . --bc-api-key $BC_API_KEY --repo-id $CODEBUILD_ACCOUNT_ID/$CODEBUILD_PROJECT --branch $CODEBUILD_GIT_BRANCH -o cli -o junitxml --output-file-path console,test_results.xml
reports:
  prisma-cloud-infrastructure-security:
    files:
       - test_results.xml
    discard-paths: yes
    file-format: JunitXml
