on: [push,pull_request]

name: OWASP dependency-check Action
jobs:
  owasp-dependency-check:
    name: OWASP dependency-check
    runs-on: ubuntu-latest
    steps:
      - name: Install dependency-check
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install dependency-check

      - name: Checkout
        uses: actions/checkout@v3

      - name: run scan
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          ls -al
          dependency-check -o reports --prettyPrint --project "Demo Project Terraform" -s . --disableOssIndex
          # add --failOnCVSS 7 to break build on CVSS score >=7
      - name: Archive scan report
        uses: actions/upload-artifact@v3
        with:
          name: owasp dependency-check reports
          path: reports
