name: build
on:
  pull_request
jobs:
#   checkov-job:
#     runs-on: ubuntu-latest
#     name: checkov-action
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2

#       - name: Run Checkov action
#         id: checkov
#         uses: bridgecrewio/checkov-action@master
#         with:
#           directory: terraform/
  yor-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 0
      - name: Run yor action
        uses: bridgecrewio/yor-action@main
